### ISSUE TITLE
按照这个方法之后，执行gulp正常，但是gulp --production是不正常的

### ISSUE THREAD

**Issue by tianyirenjian** [ElementUI/element-in-laravel-starter#3]
你好，报错信息如下图:

![qq 20161022185652](https://cloud.githubusercontent.com/assets/3616700/19618889/900454ee-9889-11e6-8082-3973856fcb4f.jpg)

我是新开的一个项目，并没有克隆你的，但是相关代码都是按照你的方法修改过的。

**Comment by tianyirenjian** [comment]
我复制了一遍错误信息：

```
{lamb} gulp --production
[18:52:56] Using gulpfile E:\codes\bookmarks\gulpfile.js
[18:52:56] Starting 'all'...
[18:52:56] Starting 'sass'...
[18:52:57] Finished 'sass' after 1.5 s
[18:52:57] Starting 'webpack'...
{ Error
    at new JS_Parse_Error (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (E:\codes\bookmarks\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
  message: 'E:\\codes\\bookmarks\\app.js: SyntaxError: Unexpected token: operator (>)',
  fileName: 'E:\\codes\\bookmarks\\app.js',
  lineNumber: 7619,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1542:11)\n    at croak (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2103:9)\n
   at expr_atom (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2630:9)\n    at maybe_unary (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2792:19)\n    at expr_ops (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2827:24)\n    at maybe_conditional (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2832:20)\n    at maybe_assign (eval at <anonymous> (E:\\codes\\bookmarks\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2856:20)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
```

**Comment by xyzget** [comment]
问题解决了吗？

**Comment by tianyirenjian** [comment]
还是没有。现在发现js变化太大了，引入了，我也看不懂不知道怎么用了。使用 ElementUI/element-starter 里面的方法生成了js文件，也不会用，恶补es6中。。

**Comment by csvwolf** [comment]
感觉可能是这个问题：<https://github.com/JeffreyWay/laravel-elixir-webpack-official/pull/28>

官方提供的套装确实比较有毒……其实我也觉得直接用webpack会比较方便

**Comment by tianyirenjian** [comment]
恩，现在先不弄了，很多基础的知识不懂。先学完es6，再学下vue2.0到时候应该就会用了。谢谢你。

我看到你们有提供cdn的可以使用，但是还是建议提供一个压缩包的版本，下载下来比较快。

**Comment by csvwolf** [comment]
@tianyirenjian 你指的压缩包是？🤖把cdn引用里的下载下来就行了吧，主要是现在前端库引入方式和过去已经有很大区别了，其实这种过去的引入方式很少用了👻

**Comment by tianyirenjian** [comment]
我知道是cdn的下载下来，可是还有些字体文件，svg文件什么的。😄别的我会通过laravel的elixir生成了，剩下的前后台不通用的，我就用直接引入的方式了。

**Comment by ibmsoft** [comment]
有解决方法了吗?

**Comment by QingWei-Li** [comment]
@tianyirenjian 你可以在 release 页面下载

**Comment by csvwolf** [comment]
提了一个issue等官方修复，感觉还是要挺久的，上一个issue提了一个月刚修掉:doggy：
<https://github.com/JeffreyWay/laravel-elixir-webpack-official/issues/34>

**Comment by csvwolf** [comment]
@tianyirenjian @ibmsoft @xyzget 暂时引入了那个pr的修复包，如果官方合入就可以直接用了。

目前 starter 已经可以进行`gulp --production`了 

<https://github.com/ElementUI/element-in-laravel-starter/commit/a7ce38ffc720c1ccc58aeac7be982d9d942d32ad>

**Comment by QingWei-Li** [comment]
@tianyirenjian 现在 CDNJS 可以用了 https://cdnjs.com/libraries/element-ui

**Comment by tianyirenjian** [comment]
好的，谢谢你们。😄
