### ISSUE TITLE
element gulp production  遇到问题

### ISSUE THREAD

**Issue by Gavin-zsl** [ElementUI/element-in-laravel-starter#4]
你好，我想问下我运行gulp的时候一切正常，运行gulp --production 打包的时候就出现错误。

{ Error
    at new JS_Parse_Error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
  message: '/Projects/img/element-icons.09162bc.svg: SyntaxError: Unexpected token: operator (<)',
  fileName: '/Projects/img/element-icons.09162bc.svg',
  lineNumber: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at croak (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)\n    at expr_atom (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)\n    at maybe_unary (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)\n    at expr_ops (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)\n    at maybe_conditional (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)\n    at maybe_assign (eval at <anonymous> (/Projects/cms2/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }

**Comment by csvwolf** [comment]
这个问题在这个issue里应该解决了，请问你用的是最新的版本吗？#3 

另外`yarn`的形式安装似乎不会安装到修复的包，只有`npm`才可以。

**Comment by Gavin-zsl** [comment]
"element-ui": "^1.0.0-rc.8",  我安装的版本是这个

**Comment by csvwolf** [comment]
@Gavin-zsl 哦不是，你`clone`的是最新的吗，README文末的教程没有更新，还是旧的。

**Comment by Gavin-zsl** [comment]
我执行的是这个 npm install element-ui@next -S   下载到的版本

**Comment by csvwolf** [comment]
@Gavin-zsl 我指的是element-in-laravel-starter的

**Comment by Gavin-zsl** [comment]
ok,问题解决了，谢谢
